# Generated by Django 5.0.4 on 2024-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.TextField(default=''),
        ),
    ]
